title: Sravan Varala
logo: /assets/img/Srarvan_Linkedin.JPG
description: Optimist with strong interest in exploring solutions and adding skills.

description:
  <p align="center">
  <a href="https://www.linkedin.com/in/sravan-varala/">LinkedIn</a> |
  <a href="https://github.com/varalasravan">GitHub</a>

  </p>



theme: jekyll-theme-minimal
